# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Posy-Plugin-Log4perl
version:      0.2
version_from: lib/Posy/Plugin/Log4perl.pm
installdirs:  site
requires:
    Log::Log4perl:                 0.51
    Posy:                          0.92
    Posy::Core:                    0.92
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
